spring.application.name=springboot-application

#spring.datasource.url=jdbc:postgresql://db:5432/dev
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update


spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

spring.sql.init.mode=always
spring.sql.init.continue-on-error=false
spring.jpa.hibernate.ddl-auto=create
