spring.application.name=springboot-application

spring.datasource.url=${SPRING_DATASOUECE_URL}
spring.datasource.username=${SPRING_DATASOUECE_USERNAME}
spring.datasource.password=${SPRING_DATASOUECE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver