spring.application.name=springboot-application

#spring.datasource.url=jdbc:postgresql://db:5432/dev
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update


spring.datasource.url=jdbc:postgresql://dpg-da0l2rdg1s2s73bta6a0-a:5432/mtakano_springboot_sql
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=y4f5pt1Qa36Hu7E1RQL5esRGjAKzAgKG
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

