CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

-- 2「初期データ（テストユーザー）」の投入処理
DELETE FROM users WHERE email = 'hokusai@fugaku.com';
INSERT INTO users (name, email, password)
VALUES ('katsushika', 'hokusai@fugaku.com', 'fugaku36');