CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

-- 2「初期データ（テストユーザー）」の投入処理
INSERT INTO users (name, email, password)
VALUES ('テストユーザー', 'test@email.com', '$2a$10$8.UnVuG9HHgffUDAlk8q7uy5shNypmieOXOMNJv6D6YUX6E8b1CgK')
ON CONFLICT (email) DO NOTHING;